version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo pre build started on `date`
      - docker info
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/twitch-ms-1.0-RELEASE.jar