version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo pre build started on `date`
      - PYTHON=python2 amazon-linux-extras enable docker
      - yum -y install amazon-ecr-credential-helper
      - chmod u+x setup-docker-config.sh
      - ./setup-docker-config.sh
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/twitch-ms-1.0-RELEASE.jar